---
title: "Initial Korean covid 19"
author: "kelly Acevedo"
date: "4/2/24"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=2)
require(tidyverse)
require(tigerstats)
require(lubridate)
kRdata <- read.csv(file = 'kRdata.csv')
kRdata <- kRdata %>%
mutate(across(where(is.character), as.factor))

```
### Data is from the Patient_Info dataset from South Korea 1 Jan to 1 May 2020
### This data was retrieved from a downloadable zip file from kaggle

Some of the data was uncoded for sex - sex must be just male or female
77 of the data entries were coded sex  as blank, so we omit these.
state of a patient must be died or alive - we adjust that as well   
  
# Your Question - Is dying independent of sex?


$H_0$: There is no difference in death rate based on gender. 

$H_A$: There is a difference in death rate based on gender.

#Methods

Have the Variables for this study which are Sex and result. 

We want to find out if result depends on sex which it would be a categorical variable, sex is a categorical variable. 

So we use the Cat ~ Cat helper file. 

## Graphical results - use ggplot commands to do this  



  





  
## Numerical results


## Inferential results 




## Conclusions

